### ISSUE TITLE
Product descriptions not being rendered

### ISSUE THREAD

**Issue by nerdenough** [CrystallizeAPI/crystallize-frontend-boilerplate#19]
It appears that the description is only being returned with `kind` and `textContent`, but not `type`, and so just returning `<br/>` instead: https://github.com/CrystallizeAPI/crystallize-content-chunk/blob/master/src/react-chunk.jsx#L32-L40

**Comment by hakonkrogh** [comment]
Did a test now with the [updated renderer for content](https://github.com/CrystallizeAPI/crystallize-content-transformer/blob/master/src/react.jsx), and now it renderers fine.
