### ISSUE TITLE
Change To US Currency

### ISSUE THREAD

**Issue by stunjiturner** [CrystallizeAPI/crystallize-frontend-boilerplate#4]
```  const createOrderResult = await klarna.createOrder({
          cart: klarna.crystallizeBasketToKlarnaCart(validatedBasket),
          purchase_country: 'US',
          purchase_currency: 'USD',
          locale: 'en-US',
```
I have an error

```
Error: {
  "http_status_code" : 401,
  "http_status_message" : "Unauthorized",
  "internal_message" : "Unauthorized"
}
    at Object.createOrder (/Users/stunjiturner/Downloads/crystallize-frontend-boilerplate-master/node_modules/@crystallize/node-klarna/v2/createOrder.js:38:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by hakonhk** [comment]
Hi,

These messages are coming from https://www.npmjs.com/package/@crystallize/node-klarna, but let's have the discussion here for now.
Do you have the Klarna env values set?

KLARNA_MODE ("prod" or "test")
KLARNA_MERCHANT_ID
KLARNA_STORE_NAME
KLARNA_SHARED_SECRET
KLARNA_TERMS_URI

**Comment by stunjiturner** [comment]
On Dec 26, 2018, 3:43 PM -0500, Håkon Krogh <notifications@github.com>, wrote:
> Hi,
> These messages are coming from https://www.npmjs.com/package/@crystallize/node-klarna, but let's have the discussion here for now.
> Do you have the Klarna env values set?
> KLARNA_MODE ("prod" or "test")
> KLARNA_MERCHANT_ID
> KLARNA_STORE_NAME
> KLARNA_SHARED_SECRET


Is that the password

**Comment by hakonhk** [comment]
KLARNA_SHARED_SECRET would be the password if you like. It is what you find in the [Klarna merchants settings page](https://merchants.klarna.com/settings/store_show_store_view) under "Shared secret".

**Comment by stunjiturner** [comment]
Is that the password

**Comment by stunjiturner** [comment]
<img width="1048" alt="screen shot 2018-12-26 at 3 47 32 pm" src="https://user-images.githubusercontent.com/1497244/50456949-f88de700-0925-11e9-96b3-7e636668c95e.png">

**Comment by hakonhk** [comment]
Hm. This looks like a different version of the API then what we currently is supporting. Is it version 3?

**Comment by stunjiturner** [comment]
https://playground.us.portal.klarna.com/#realm=merchants

**Comment by hakonhk** [comment]
> [playground.us.portal.klarna.com/#realm=merchants](https://playground.us.portal.klarna.com/#realm=merchants)

This is a protected page which I don't have access too..

**Comment by stunjiturner** [comment]
just wanted you to see the URL

**Comment by hakonhk** [comment]
Is there any mention of the endpoint to the Klarna REST api?

**Comment by stunjiturner** [comment]
no

**Comment by stunjiturner** [comment]
where do you got sign up for klarna?

**Comment by stunjiturner** [comment]
is there a slack channel for Crystallize

**Comment by hakonhk** [comment]
In a Scandinavian branch, but this is definitely looks like an API version thing. It looks like you are on version 3.

[V2](https://developers.klarna.com/en/gb/kco-v2/checkout-api/#authorization) requires a different way of authenticating than [v3](https://developers.klarna.com/en/gb/kco-v3/checkout/2-render-the-checkout/#authentication)

The @crystallize/node-klarna package is currently only operating with v2. V3 support is planned, but not on the roadmap in the near future. I suggest you follow the API documentation for v3 and integrate directly.

And yes, we do have a Slack channel 😃 [crystallizecommunity.slack.com](https://crystallizecommunity.slack.com)

**Comment by stunjiturner** [comment]
can I get a invite to can@trbzink.com

**Comment by stunjiturner** [comment]
purchase_country: 'NO',
          purchase_currency: 'NOK',
          locale: 'nb-no',

**Comment by stunjiturner** [comment]
the createOrder.js in node-klarna, does not take the options, seems to be hardcoded, even though the function accepts { option } pararameters, just does not seem to use them at all.

https://github.com/CrystallizeAPI/node-klarna/blob/master/v2/createOrder.js

**Comment by hakonhk** [comment]
> the createOrder.js in node-klarna, does not take the options, seems to be hardcoded, even though the function accepts { option } pararameters, just does not seem to use them at all.
> 
> [CrystallizeAPI/node-klarna:v2/createOrder.js@`master`](https://github.com/CrystallizeAPI/node-klarna/blob/master/v2/createOrder.js)

It does in fact. Line 20; it takes the option parameter as the second argument in the deep-assign, so everything you pass as options should be passed in
